version: '3'
services:
  api:
    build:
      context: ../..
      dockerfile: apps/llp-performance-aggregate-api/Dockerfile
    image: 20xlevel/llp-performance-aggregate-api:${PREFIX:-dev}
    env_file:
      - .env
  worker:
    build:
      context: ../..
      dockerfile: apps/llp-performance-aggregate-worker/Dockerfile
    image: 20xlevel/llp-performance-aggregate-worker:${PREFIX:-dev}
    env_file:
      - .env
